customers/urls.py
from django.urls import path, include
from . import views

from rest_framework.routers import DefaultRouter

# Code to call REST API views 

router = DefaultRouter()
router.register(r'customer', views.CustomerViewSet)

app_name = 'customers'
urlpatterns = [
    # routes for user pages
    path('', include(router.urls)),

    # routes for admin pages
    path('admin-customers/', views.AllCustomersView.as_view(), name="admin-customers"),
    # path('admin-customers/<int:pk>/update/', views.UpdateCustomerView.as_view(), name="customer-update"),
    
    path('admin-customers/<int:pk>/update/', views.updateCustomer, name="customer-update"),
    
]

mensa-django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users import views as my_user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin-menu/', include('menus.urls')),

    path('registration/', my_user_views.registration, name='registration'),
    path('login/', auth_views.LoginView.as_view(template_name='admin_temp/user/login.html'), name='login'),
    path('profile/', my_user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='admin_temp/user/logout.html'), name='logout'),
    
    # code for django-vue integration
    # path('', TemplateView.as_view(template_name='index.html')),
    path('notes/',include('testApp.urls')),
    path('customer/', include('customers.urls')),
    path('menu/',include('menus.urls')),
    path('orders/',include('orders.urls')),
    path('invoice/',include('invoices.urls')),
    path('wallet/',include('wallets.urls')),
    path('coupon/',include('coupon.urls')),
    path('creditcard/',include('creditCard.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menus/urls.py
"""
4. Modify urls

import default rourter to call django rest framework interface
import  views from the app
import modules to use path and include methods
"""

from rest_framework.routers import DefaultRouter
from menus import views
from django.urls import path, include

#from rest_framework import routers

# Code to call REST API views 

#router = routers.SimpleRouter()
router = DefaultRouter()
router.register(r'menu', views.MenuViewSet)

urlpatterns = [
    # routes for user pages
    path('', include(router.urls)),

    # routes for admin pages
    path('admin-menu/', views.MenuView.as_view(), name="admin-menu"),
    path('admin-menu/new/', views.AddMenuView.as_view(), name="menu-create"),
    path('admin-menu/<int:pk>/update/', views.UpdateMenuView.as_view(), name="menu-update"),
    path('admin-menu/<int:pk>/delete/', views.DeleteMenuView.as_view(), name="menu-delete"),
]

# Code to call admin views 

# app_name = 'menus'
# urlpatterns = [
#     path('', views.MenuView.as_view(), name="menu"),
    
    # path('add-menu/', views.AddMenuView.as_view(), name="add-menu"),
# ]

customers/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.

TYPE_CHOICES = (
    ("Student", "Student"),
    ("Guest", "Guest"),
    ("Attendant", "Attendant"),
)

class Customer(models.Model):
    # user    = models.OneToOneField(User, on_delete=models.CASCADE) # one to one relationship
    first_name    = models.CharField(max_length=100)
    last_name     = models.CharField(max_length=100)
    email_address = models.EmailField(max_length=150, unique=True)
    # password = forms.CharField(max_length=32, widget=forms.PasswordInput) 
    password      = models.CharField(max_length=32) 
    address       = models.TextField(null=True, blank=True)
    type          = models.CharField(max_length=120, choices=TYPE_CHOICES, default="Guest")
    mobile        = models.CharField(max_length=50, null=True, blank=True)

    # def __str__(self):
    #     return f'{self.first_name} Customer' 

    # def save(self):
    #     super().save()

    def get_address(self):
        if len(self.address) > 15:
            return self.address[:15] + " ...."
        return self.address

menus/models.py
"""
1. Modify the model for the app

Import models module from django.db
"""

from django.db import models
from django.urls import reverse

# Create your models here.

CATEGORY_CHOICES = (
    ("Veg", "Veg"),
    ("Non-Veg", "Non-Veg"),
    ("Salads", "Salads"),
    ("Desserts", "Desserts"),
    ("Fruits", "Fruits"),
    ("Beverages", "Beverages"),
    ("Favorite", "Favorite"),
)

STATUS_CHOICES = (
    ("Available", "Available"),
    ("Not Available", "Not Available"),
)

class Menu(models.Model):
    title           = models.CharField(max_length=50)
    description     = models.TextField(null=True, blank=True)
    category        = models.CharField(max_length=120, choices=CATEGORY_CHOICES)
    status          = models.CharField(max_length=120, choices=STATUS_CHOICES, default="Not Available")
    calories        = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    price_student   = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    price_guest     = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    price_attendant = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    day             = models.DateField()
    slug            = models.SlugField(unique=True)
    quantity        = models.IntegerField(default=0)
    timestamp       = models.DateTimeField(auto_now_add=True, auto_now=False)
    update          = models.DateTimeField(auto_now_add=False, auto_now=True)
    
    def __str__(self):
         return self.title

    def get_description(self):
        if len(self.description) > 50:
            return self.description[:50] + " ........."
        return self.description

    def get_absolute_url(self):
        #return reverse('menus:add-menu', kwargs={'pk': self.pk})
        return reverse('admin-menu')

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # one to one relationship
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile' #f means abstract method

    def save(self):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 400 or img.width > 400:
            output_size = (400, 400)
            img.thumbnail(output_size)
            img.save(self.image.path)

customers/forms.py
from django import forms
from django.contrib.auth.models import User
from . models import Customer

"""
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']
"""


class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'email_address', 'address', 'type', 'mobile']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from . models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

customers/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.contrib.auth.models import User
from . models import Customer

from customers.serializers import CustomerSerializer
from rest_framework import viewsets
from rest_framework.decorators import permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.permissions import AllowAny

from django.contrib.auth.decorators import login_required
# from . forms import UserUpdateForm, CustomerUpdateForm
from . forms import CustomerUpdateForm

from django.views.generic import (
    ListView,
    # CreateView,
    UpdateView,
    DeleteView,
    #DetailView,
)


# Allowing any user to access the view
@permission_classes((AllowAny, ))

# View for user interface
class CustomerViewSet(viewsets.ModelViewSet):

    permission_classes = (IsAuthenticated,)
    queryset = Customer.objects.all() #Select Menu
    serializer_class = CustomerSerializer #Serelize data


# Views for admin interface
class AllCustomersView(LoginRequiredMixin, ListView):
    template_name = "admin_temp/user/customers.html"
    model = Customer
    paginate_by = 5

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set


@login_required
def updateCustomer(request, pk):
    customer   = Customer.objects.get(pk=pk)
    if request.method == 'POST':
        c_form = CustomerUpdateForm(request.POST, request.FILES, instance=customer)

        if c_form.is_valid():
            c_form.save()
            messages.success(request, f'Customer Info has been Updated!')
            return redirect('customers:admin-customers')

    else:
        c_form = CustomerUpdateForm(instance=customer)    
  
    context = { 'c_form': c_form }

    return render(request, 'admin_temp/user/edit_customer.html', context) 

"""
class UpdateCustomerView(LoginRequiredMixin, UpdateView):
    template_name = "admin_temp/user/edit_customer.html"
    model = Customer
    fields = [
        'first_name', 'last_name', 'email_address', 'address', 'type', 'mobile'
    ]

    def form_valid(self, form):
        return super().form_valid(form)
"""

"""
@login_required
def updateCustomer(request, pk):
    u_customer = User.objects.get(pk=pk)
    customer   = Customer.objects.get(user_id=pk)
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=u_customer)
        c_form = CustomerUpdateForm(request.POST, request.FILES, instance=customer)

        if u_form.is_valid() and c_form.is_valid():
            u_form.save()
            c_form.save()
            messages.success(request, f'Customer Info has been Updated!')
            return redirect('customers:admin-customers')

    else:
        u_form = UserUpdateForm(instance=u_customer)
        c_form = CustomerUpdateForm(instance=customer)    
  
    context = { 'u_form': u_form, 'c_form': c_form }

    return render(request, 'admin_temp/user/edit_customer.html', context)   
"""

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from . forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


def registration(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your Account has been created! You are now able to login')
            return redirect('login')
    else:
        form = UserRegisterForm() 
    return render(request, 'admin_temp/user/registration.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your Account has been Updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)    
  
    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'admin_temp/user/profile.html', context)    

templates/admin_temp/user/customers.html
{% extends '../base.html' %}

{% block head_title %}
Manage Customers
{% endblock %}

{% block styles %}
a.btn {
    -webkit-transform: scale(0.8);
    -moz-transform: scale(0.8);
    -o-transform: scale(0.8);
    -webkit-transition-duration: 0.5s;
    -moz-transition-duration: 0.5s;
    -o-transition-duration: 0.5s;
}

.boxed {
    padding: 3px;
    border-radius: 5px;
}
.boxed.green {
    color: white;
    bgcolor: #FF0000;
    width: 75px;
}
.boxed.red {
    color: white;
    bgcolor: red;
    width: 103px;
}
.boxed.blue {
    color: white;
    width: 103px;
    bgcolor: blue;
}

{% endblock %}

{% block content %}

<section class="menu-area section-gap" id="menu">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="menu-content pb-70 col-lg-8">
                    <div class="title text-center">
                        <h1 class="mb-10">Manage Customes</h1>
                    </div>
                </div>
            </div>	
       
            <div class="filters-content">
                <div class="row grid">   
                    <div class="col-md-12 all">						
                        <div class="section-top-border">
                            <h3 class="mb-30">All Customers</h3>
                            <div class="progress-table-wrap">
                                <div class="progress-table">
                                    <div class="table-head">
                                        <div class="serial">#</div>
                                        <div class="visit">First Name</div>
                                        <div class="visit">Last Name</div>
                                        <!-- <div class="visit">Email</div> -->
                                        <div class="visit">Address</div>
                                        <div class="visit">Type</div>
                                        <div class="visit">Mobile</div>
                                        <div class="visit">Action</div>
                                    </div>
                                    {% for customer in object_list %}  
                                    <div class="table-row">
                                        <div class="serial">{{ customer.id }}</div>
                                        <div class="visit">{{ customer.first_name }}</div>
                                        <div class="visit">{{ customer.last_name }}</div>
                                        <!-- <div class="visit">{{ customer.user.email }}</div> -->
                                        <div class="visit">{{ customer.get_address }}</div>
                                        <div class="visit">{{ customer.type }}</div>
                                        <div class="visit">{{ customer.mobile }}</div>
                                        <div class="visit">
                                            <a href="{% url 'customers:customer-update' customer.id %}" class="btn btn-primary btn-sm">
                                                <span class="fa fa-edit" aria-hidden="true"></span>
                                                <span><strong>Edit</strong></span>            
                                            </a>  
                                            <a href="#" onClick="return confirm('Delete This Customer?')" class="btn btn-danger btn-sm">
                                                <span class="fa fa-remove" aria-hidden="true"></span>
                                                <span><strong>Delete</strong></span>            
                                            </a> 
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                                    
                </div>
                
            </div>
            <br /><br />
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
    
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}
    
                {% if page_obj.has_next %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
    
            {% endif %}
    
        </div>
    </section>

{% endblock %}


{% block jquery %}
//any changes
{% endblock %}

templates/admin_temp/user/edit_customer.html
{% extends '../base.html' %}

{%  load crispy_forms_tags %}

{% block head_title %}
Update Customer
{% endblock %}

{% block styles %}

{% endblock %}

{% block content %}

<section class="menu-area section-gap" id="menu">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">
                    <h1 class="mb-10">Update Customer Information</h1>
                </div>
            </div>
        </div>	

        <div class="filters-content">
            
 
                <div class="col-md-12">						
                    <div class="single-menu">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="col-md-12">
                                <fieldset class="form-group">
                                    <legend class="border-bottom mb-4">Update Information</legend>
                                    {{ u_form|crispy }}
                                    {{ c_form|crispy }}
                                </fieldset>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <input type="submit" class="btn btn-outline-info" name="submit" value="Update" />
                                </div>
                            </div>     
                        </form>								
                    </div>
                </div>

        						
            
        </div>
        
    </div>
</section>

{% endblock %}


{% block jquery %}
$('#id_day').datepicker({ uiLibrary: 'bootstrap4', iconsLibrary: 'materialicons' });
{% endblock %}

templates/admin_temp/user/login.html
{%  load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <style>
        .center-div
        {
        position: absolute;
        margin: auto;
        top: 10;
        right: 0;
        bottom: 10;
        left: 0;
        width: 600px;
        height: 600px;
        border-radius: 3px;
        background-color: #fcfcfc;
        }
    </style>

    <title>Login</title>
  </head>
  <body>
        <div class="center-div">
        
            <form method="POST" >
                {% csrf_token %}
                <div class="col-md-12">
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Login Here</legend>
                        {{ form|crispy }}
                    </fieldset>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" class="btn btn-outline-info" name="submit" value="Login" />
                    </div>
                </div>     
            </form>

            <div class="col-md-12">
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Need an Account? <a class="ml-2" href="{% url 'registration' %}">Sign Up Now</a>
                    </small>
                </div>
            </div>

        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/admin_temp/user/logout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <style>
        .center-div
        {
        position: absolute;
        margin: auto;
        top: 10;
        right: 0;
        bottom: 10;
        left: 0;
        width: 600px;
        height: 600px;
        border-radius: 3px;
        background-color: #fcfcfc;
        }
    </style>

    <title>Logged Out</title>
  </head>
  <body>
        <div class="center-div">
            
            <h2>You have been logged out</h2>

            <div class="col-md-12">
                <div class="border-top pt-3">
                    <small class="text-muted">
                        <a href="{% url 'login' %}">Login Again</a>
                    </small>
                </div>
            </div>

        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/admin_temp/user/profile.html
{% extends '../base.html' %}

{%  load crispy_forms_tags %}

{% block head_title %}
Your Profile
{% endblock %}

{% block styles %}
.card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 300px;
    margin: auto;
    text-align: center;
    font-family: arial;
  }
  
  .title {
    color: grey;
    font-size: 18px;
  }
  
  button {
    border: none;
    outline: 0;
    display: inline-block;
    padding: 8px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
    font-size: 18px;
  }
  
  a {
    text-decoration: none;
    font-size: 22px;
    color: black;
  }
  
  button:hover, a:hover {
    opacity: 0.7;
  }
{% endblock %}

{% block content %}

<section class="menu-area section-gap" id="menu">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-70 col-lg-8">
                <div class="title text-center">
                    <h2 style="text-align:center">User Profile</h2>

                    <div class="card">
                    <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" style="width:100%;">
                    <h1>{{ user.username }}</h1>
                    <p class="title">{{ user.email }}</p>
                    <!-- <p>Harvard University</p> -->
                    <!-- <div style="margin: 24px 0;">
                        <a href="#"><i class="fa fa-dribbble"></i></a> 
                        <a href="#"><i class="fa fa-twitter"></i></a>  
                        <a href="#"><i class="fa fa-linkedin"></i></a>  
                        <a href="#"><i class="fa fa-facebook"></i></a> 
                    </div>
                    <p><button>Contact</button></p> -->

                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="col-md-12">
                            <fieldset class="form-group">
                                <legend class="border-bottom mb-4">Profile Info</legend>
                                {{ u_form|crispy }}
                                {{ p_form|crispy }}
                            </fieldset>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <input type="submit" class="btn btn-outline-info" name="submit" value="Update" />
                            </div>
                        </div>     
                    </form>

                    </div>
                </div>
            </div>
        </div>	
        
    </div>
</section>

{% endblock %}


{% block jquery %}
//any changes
{% endblock %}

templates/admin_temp/user/registration.html
{%  load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <style>
        .center-div
        {
        position: absolute;
        margin: auto;
        top: 10;
        right: 0;
        bottom: 10;
        left: 0;
        width: 600px;
        height: 600px;
        border-radius: 3px;
        background-color: #fcfcfc;
        }
    </style>

    <title>Registration</title>
  </head>
  <body>
        <div class="center-div">
        
            <form method="POST" >
                {% csrf_token %}
                <div class="col-md-12">
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Register Here</legend>
                        {{ form|crispy }}
                    </fieldset>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" class="btn btn-outline-info" name="submit" value="Register" />
                    </div>
                </div>     
            </form>

            <div class="col-md-12">
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Already Have an Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
                    </small>
                </div>
            </div>

        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

<!-- <form method="post" >
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td><input type="submit" name="submit" value="Register" /></td>
                    </tr>
                </table>
            </form> -->