mensa-django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users import views as my_user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin-menu/', include('menus.urls')),

    path('registration/', my_user_views.registration, name='registration'),
    path('login/', auth_views.LoginView.as_view(template_name='admin_temp/user/login.html'), name='login'),
    path('profile/', my_user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='admin_temp/user/logout.html'), name='logout'),
    
    # code for django-vue integration
    # path('', TemplateView.as_view(template_name='index.html')),
    path('notes/',include('testApp.urls')),
    path('customer/', include('customers.urls')),
    path('menu/',include('menus.urls')),
    path('orders/',include('orders.urls')),
    path('invoice/',include('invoices.urls')),
    path('wallet/',include('wallets.urls')),
    path('coupon/',include('coupon.urls')),
    path('creditcard/',include('creditCard.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menus/urls.py
"""
4. Modify urls

import default rourter to call django rest framework interface
import  views from the app
import modules to use path and include methods
"""

from rest_framework.routers import DefaultRouter
from menus import views
from django.urls import path, include

#from rest_framework import routers

# Code to call REST API views 

#router = routers.SimpleRouter()
router = DefaultRouter()
router.register(r'menu', views.MenuViewSet)

urlpatterns = [
    # routes for user pages
    path('', include(router.urls)),

    # routes for admin pages
    path('admin-menu/', views.MenuView.as_view(), name="admin-menu"),
    path('admin-menu/new/', views.AddMenuView.as_view(), name="menu-create"),
    path('admin-menu/<int:pk>/update/', views.UpdateMenuView.as_view(), name="menu-update"),
    path('admin-menu/<int:pk>/delete/', views.DeleteMenuView.as_view(), name="menu-delete"),
]

# Code to call admin views 

# app_name = 'menus'
# urlpatterns = [
#     path('', views.MenuView.as_view(), name="menu"),
    
    # path('add-menu/', views.AddMenuView.as_view(), name="add-menu"),
# ]

orders/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import views


# Code to call REST API views 

router = DefaultRouter()
router.register(r'orders', views.OrderViewSet)

app_name = 'orders'

urlpatterns = [
    
    path('', include(router.urls)),

    path('admin-orders/', views.AllOrdersView.as_view(), name="admin-orders"),
    path('admin-orders/<int:pk>/accept/', views.acctept_or_deny, name="order-action"),
]

orders/models.py
from django.db import models

from customers.models import Customer
from menus.models import Menu

STATUS_CHOICES = (
    ("Pending", "Pending"),
    ("Aproved", "Aproved"),
    ("Canceled", "Canceled"),
)

class Order(models.Model):
    customer  = models.ForeignKey(Customer, on_delete = models.CASCADE)
    menu      = models.ManyToManyField(Menu)
    status    = models.CharField(max_length=120, choices=STATUS_CHOICES, default="Pending")
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    update    = models.DateTimeField(auto_now_add=False, auto_now=True)

    

orders/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from . models import Order
from orders.serializers import OrderSerializer

from rest_framework import viewsets
from rest_framework.decorators import permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.permissions import AllowAny

# Allowing any user to access the view
@permission_classes((AllowAny, ))

# View for user interface
class OrderViewSet(viewsets.ModelViewSet):

    permission_classes = (IsAuthenticated,)
    queryset = Order.objects.all() #Select Menu
    serializer_class = OrderSerializer #Serelize data


# View for Admin
class AllOrdersView(LoginRequiredMixin, ListView):
    template_name = "admin_temp/order/orders.html"
    model = Order
    ordering = ['-timestamp']
    paginate_by = 4

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set.select_related('customer')


def acctept_or_deny(request, pk):
    orderAction = Order.objects.get(pk=pk)
    if request.POST['action'] == "Approve":
        orderAction.status = "Aproved"

    elif request.POST['action'] == "Cancel":
        orderAction.status = "Canceled"    
    
    orderAction.save()
    
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    return HttpResponseRedirect(reverse('orders:admin-orders'))    

templates/admin_temp/order/orders.html
{% extends '../base.html' %}

{% block head_title %}
Manage Orders
{% endblock %}

{% block styles %}
a.btn {
    -webkit-transform: scale(0.8);
    -moz-transform: scale(0.8);
    -o-transform: scale(0.8);
    -webkit-transition-duration: 0.5s;
    -moz-transition-duration: 0.5s;
    -o-transition-duration: 0.5s;
}

.boxed {
    padding: 3px;
    border-radius: 5px;
}
.boxed.green {
    color: white;
    bgcolor: #FF0000;
    width: 75px;
}
.boxed.red {
    color: white;
    bgcolor: red;
    width: 103px;
}
.boxed.blue {
    color: white;
    width: 103px;
    bgcolor: blue;
}

{% endblock %}

{% block content %}

<section class="menu-area section-gap" id="menu">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="menu-content pb-70 col-lg-8">
                    <div class="title text-center">
                        <h1 class="mb-10">Manage Your Orders</h1>
                    </div>
                </div>
            </div>	
       
            <div class="filters-content">
                <div class="row grid">   
                    <div class="col-md-12 all">						
                        <div class="section-top-border">
                            <h3 class="mb-30">All Orders</h3>
                            <div class="progress-table-wrap">
                                <div class="progress-table">
                                    <div class="table-head">
                                        <div class="serial">#</div>
                                        <div class="visit">Food Menu</div>
                                        <div class="visit">Ordered By</div>
                                        <div class="visit">Status</div>
                                        <div class="visit">Order Time</div>
                                        <div class="country">Action</div>
                                    </div>
                                    {% for order in object_list %}  
                                    <div class="table-row">
                                        <div class="serial">{{ order.id }}</div>
                                        <div class="visit">
                                            {% for item in order.menu.all %}
                                               {{forloop.counter}}. {{ item.title }}<br>
                                            {% endfor %}
                                        </div>
                                        <div class="visit">{{ order.customer.user.username }}</div>
                                        <div class="visit">{{ order.status }}</div>
                                        <div class="visit">{{ order.timestamp }}</div>
                                        <div class="country">
                                            <form action="{% url 'orders:order-action' order.id %}" method="post">
                                                {% csrf_token %}
                                                {% if order.status == 'Pending' %}
                                                <input type="submit" name="action" value="Approve" class="btn btn-primary btn-sm" />
                                                <input type="submit" name="action" value="Cancel" class="btn btn-danger btn-sm" />
                                                {% elif order.status == 'Aproved' %}
                                                <input type="submit" name="action" value="Cancel" class="btn btn-danger btn-sm" />
                                                {% endif %}
                                                
                                            </form>          
                                            </a>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                                    
                </div>
                
            </div>
            <br /><br />
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}
    
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}
    
                {% if page_obj.has_next %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
    
            {% endif %}
    
        </div>
    </section>

{% endblock %}


{% block jquery %}
//any changes
{% endblock %}