customers/urls.py
from django.urls import path, include
from . import views

from rest_framework.routers import DefaultRouter

# Code to call REST API views 

router = DefaultRouter()
router.register(r'customer', views.CustomerViewSet)

app_name = 'customers'
urlpatterns = [
    # routes for user pages
    path('', include(router.urls)),

    # routes for admin pages
    path('admin-customers/', views.AllCustomersView.as_view(), name="admin-customers"),
    # path('admin-customers/<int:pk>/update/', views.UpdateCustomerView.as_view(), name="customer-update"),
    
    path('admin-customers/<int:pk>/update/', views.updateCustomer, name="customer-update"),
    
]

invoices/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'invoice', views.InvoiceViewSet)

app_name = 'invoices'

urlpatterns = [
    # routes for user pages
    path('', include(router.urls)),

    # routes for admin pages
    path('admin-invoices', views.AllInvoicesView.as_view(), name="admin-invoices"),
]

mensa-django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users import views as my_user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin-menu/', include('menus.urls')),

    path('registration/', my_user_views.registration, name='registration'),
    path('login/', auth_views.LoginView.as_view(template_name='admin_temp/user/login.html'), name='login'),
    path('profile/', my_user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='admin_temp/user/logout.html'), name='logout'),
    
    # code for django-vue integration
    # path('', TemplateView.as_view(template_name='index.html')),
    path('notes/',include('testApp.urls')),
    path('customer/', include('customers.urls')),
    path('menu/',include('menus.urls')),
    path('orders/',include('orders.urls')),
    path('invoice/',include('invoices.urls')),
    path('wallet/',include('wallets.urls')),
    path('coupon/',include('coupon.urls')),
    path('creditcard/',include('creditCard.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menus/urls.py
"""
4. Modify urls

import default rourter to call django rest framework interface
import  views from the app
import modules to use path and include methods
"""

from rest_framework.routers import DefaultRouter
from menus import views
from django.urls import path, include

#from rest_framework import routers

# Code to call REST API views 

#router = routers.SimpleRouter()
router = DefaultRouter()
router.register(r'menu', views.MenuViewSet)

urlpatterns = [
    # routes for user pages
    path('', include(router.urls)),

    # routes for admin pages
    path('admin-menu/', views.MenuView.as_view(), name="admin-menu"),
    path('admin-menu/new/', views.AddMenuView.as_view(), name="menu-create"),
    path('admin-menu/<int:pk>/update/', views.UpdateMenuView.as_view(), name="menu-update"),
    path('admin-menu/<int:pk>/delete/', views.DeleteMenuView.as_view(), name="menu-delete"),
]

# Code to call admin views 

# app_name = 'menus'
# urlpatterns = [
#     path('', views.MenuView.as_view(), name="menu"),
    
    # path('add-menu/', views.AddMenuView.as_view(), name="add-menu"),
# ]

orders/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from . import views


# Code to call REST API views 

router = DefaultRouter()
router.register(r'orders', views.OrderViewSet)

app_name = 'orders'

urlpatterns = [
    
    path('', include(router.urls)),

    path('admin-orders/', views.AllOrdersView.as_view(), name="admin-orders"),
    path('admin-orders/<int:pk>/accept/', views.acctept_or_deny, name="order-action"),
]

templates/admin_temp/common/banner.html
<section class="about-banner relative">
    <div class="overlay overlay-bg"></div>
    <div class="container">				
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Menus				
                </h1>	
                <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="menu.html"> Menus</a></p>
            </div>	
        </div>
    </div>
</section>

templates/admin_temp/common/footer.html
<footer class="footer-area">
    <div class="footer-widget-wrap">
        <div class="container">
            <div class="row section-gap">
                <div class="col-lg-4  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h4>Opening Hours</h4>
                        <ul class="hr-list">
                            <li class="d-flex justify-content-between">
                                <span>Monday - Friday</span> <span>08.00 am - 10.00 pm</span>
                            </li>
                            <li class="d-flex justify-content-between">
                                <span>Saturday</span> <span>08.00 am - 10.00 pm</span>
                            </li>
                            <li class="d-flex justify-content-between">
                                <span>Sunday</span> <span>08.00 am - 10.00 pm</span>
                            </li>																				
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h4>Contact Us</h4>
                        <p>
                            56/8, los angeles, rochy beach, Santa monica, United states of america - 1205
                        </p>
                        <p class="number">
                            012-6532-568-9746 <br>
                            012-6532-569-9748
                        </p>
                    </div>
                </div>						
                <div class="col-lg-4  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h4>Newsletter</h4>
                        <p>You can trust us. we only send promo offers, not a single spam.</p>
                        <div class="d-flex flex-row" id="mc_embed_signup">


                              <form class="navbar-form" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get">
                                <div class="input-group add-on align-items-center d-flex">
                                      <input class="form-control" name="EMAIL" placeholder="Your Email address" onFocus="this.placeholder = ''" onBlur="this.placeholder = 'Your Email address'" required="" type="email">
                                    <div style="position: absolute; left: -5000px;">
                                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                    </div>
                                  <div class="input-group-btn">
                                    <button class="genric-btn"><span class="lnr lnr-arrow-right"></span></button>
                                  </div>
                                </div>
                                  <div class="info mt-20"></div>
                              </form>
                        </div>
                    </div>
                </div>						
            </div>					
        </div>					
    </div>
    <div class="footer-bottom-wrap">
        <div class="container">
            <div class="row footer-bottom d-flex justify-content-between align-items-center">
                <p class="col-lg-8 col-mdcol-sm-6 -6 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                <ul class="col-lg-4 col-mdcol-sm-6 -6 social-icons text-right">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                    <li><a href="#"><i class="fa fa-behance"></i></a></li>           
                </ul>
            </div>						
        </div>
    </div>
</footer>

templates/admin_temp/common/header.html
<header id="header">
    <div class="header-top">
        <div class="container">
              <div class="row justify-content-center">
                  <div id="logo"></div>
              </div>			  					
        </div>
    </div>
    
    <div class="row align-items-left justify-content-left d-flex">			
        <nav id="nav-menu-container">
            <ul class="nav-menu">
              <li>
                <h1><a href="{% url 'menu-create' %}" class="primary-btn text-uppercase" >Add Food Items</a> </h1>
              </li>
    </div>
    <!-- #navbar -->          
    {% include './navbar.html' %}
    <!-- #End navbar -->
    
</header>

templates/admin_temp/common/navbar.html
<div class="container main-menu">
    <div class="row align-items-center justify-content-center d-flex">			
      <nav id="nav-menu-container">
        <ul class="nav-menu">
        
        
          <li><a href="{% url 'admin-menu' %}">Food Menu</a>
                        
                        
                        <ul>
                    
                <div class="row align-items-center justify-content-center d-flex">			
      <nav id="nav-menu-container">
      
                <li><a href="{% url 'admin-menu' %}"> View Current Menu</a></li>
                
                
                </div>
    
                  </ul>
              </li>
              
              
                            
          
          <li><a href="{% url 'orders:admin-orders' %}">Orders</a>
          
                      <ul>
                    
                <div class="row align-items-center justify-content-center d-flex">			
      <nav id="nav-menu-container">
                
                <li><a href="{% url 'orders:admin-orders' %}"> Manage Orders</a></li>

                </li>
                
                </div>
    
                  </ul>
              </li>
              
          
          <li><a href="menu.html">Invoices</a>
          
          <ul>
              <li><a href="{% url 'invoices:admin-invoices' %}">Invoice History</a></li>
             
              <li><a href="blog-single.html">Report Generator</a>
                  <ul>
            
                
                <div class="row align-items-center justify-content-center d-flex">			
      <nav id="nav-menu-container">
      
                <li><a href="blog-single.html"> Daily</a></li>
                <li><a href="blog-single.html"> Weekly</a></li>
                <li><a href="blog-single.html"> Monthly</a></li>
                <li><a href="blog-single.html"> Customize</a></li>
                
                
                </div>
    
                  </ul>
              </li>
          </ul>
          
          
          </li>
          
          
          <li><a href="gallery.html">Profile Management</a>
          
          <ul>
              <li><a href="{% url 'customers:admin-customers' %}">Customer Management</a></li>
              <li><a href="#">Admin Management</a></li>
          </ul>
          
          
          </li>
          
          
          <li class="menu-has-children"><a href="">Settings</a>
            <ul>
              <li><a href="{% url 'profile' %}">Personal Information</a></li>
              <li><a href="blog-single.html">Notifications</a></li>
              <li><a href="blog-single.html">Language</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
            </ul>
          </li>	
        
        </ul>
      </nav><!-- #nav-menu-container -->					      		  
    </div>
</div>